import cx from 'classnames';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Noto_Sans } from 'next/font/google';

import ThemeToggle from '@/components/theme-toggle';

import './globals.scss';

const notoSans = Noto_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'News Aggregator App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cx(notoSans.className, 'text-sm dark:bg-black lg:text-base')}
      >
        <ThemeProvider attribute='class'>
          <main className='responsive-content mb-8 flex flex-col gap-y-2'>
            {children}
            <ThemeToggle />
          </main>
        </ThemeProvider>
        <div id='modal' />
      </body>
    </html>
  );
}
